from PyQt6.QtCore import QObject
from models.data_manager.database_manager import DatabaseManager
from models.telemetry_simulation.trip_simulator import TripSimulator 

class EcoCoachController(QObject):
    def __init__(self, view, vehicle_model, username):
        super().__init__()
        self.view = view
        self.vehicle_model = vehicle_model
        self.username = username
        self.current_vin = None
        
        # --- FIX: Ensure the database has the new GNSS/IMU columns before we ever query them! ---
        TripSimulator._ensure_telemetry_columns()

    def set_active_vin(self, vin):
        """Triggered by the top dropdown menu to switch cars."""
        self.current_vin = vin
        self.load_eco_data()

    def load_eco_data(self):
        """Fetches the GNSS/IMU data from the database and pushes it to the UI."""
        if not self.current_vin:
            return

        conn = DatabaseManager.get_connection()
        cursor = conn.cursor()
        
        # Extract the exact Strada et al. metrics generated by our physics engine
        cursor.execute('''
            SELECT t.driving_score, t.green_speed_pct, 
                   t.harsh_events_avg, t.harsh_events_heavy, t.harsh_events_extreme,
                   c.powertrain
            FROM vehicle_telemetry t
            JOIN vehicles v ON t.vin = v.vin
            JOIN car_models c ON v.model_id = c.id
            WHERE t.vin = ?
        ''', (self.current_vin,))
        
        row = cursor.fetchone()
        conn.close()
        
        if row:
            score, green_pct, h_avg, h_hvy, h_ext, powertrain = row
            
            # Defensive checks in case the database hasn't been simulated yet
            score = score if score is not None else 100
            green_pct = green_pct if green_pct is not None else 0
            h_avg = h_avg if h_avg is not None else 0
            h_hvy = h_hvy if h_hvy is not None else 0
            h_ext = h_ext if h_ext is not None else 0
            
            # Send the data to the View!
            self.view.update_dashboard(score, green_pct, h_avg, h_hvy, h_ext, powertrain)